"""add_products

Revision ID: babe315b24a8
Revises: 6a9b87b070c0
Create Date: 2025-11-05 23:18:07.131898

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "babe315b24a8"
down_revision: Union[str, Sequence[str], None] = "6a9b87b070c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("avaibility", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("product_id"),
        schema="coffee_order_service_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products", schema="coffee_order_service_schema")
    # ### end Alembic commands ###
