name: CI Pipeline

on:
  push:
    branches: [dev, master, feature/**]
  pull_request:
    branches: [dev, master]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.*"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . ruff pytest


      - name: Run Ruff linter
        run: |
          ruff check .

      - name: Run tests
        run: |
          pytest -v || true

      - name: Test Docker build image
        run: |
          docker build -t test-build -f infra/Dockerfile .
