name: CI Pipeline

on:
  push:
    branches: [dev, master, feature/**]
  pull_request:
    branches: [dev, master]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install . ruff pytest


      - name: Run Ruff linter
        run: |
          ruff check .

      - name: Run tests
        run: |
          pytest -v || true

      - name: Test Docker build
        run: |
          docker build -t test-build .
